-- CARWORKSHOP DATABASE --
-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 17:23:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carworkshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carworkshop` ;

-- -----------------------------------------------------
-- Schema carworkshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carworkshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `carworkshop` ;

-- -----------------------------------------------------
-- Table `carworkshop`.`cabecera_diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`cabecera_diagnostico` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`cabecera_diagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `id_vehiculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_vehiculo` (`id_vehiculo` ASC) VISIBLE,
  CONSTRAINT `cabecera_diagnostico_ibfk_1`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `carworkshop`.`vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`cita` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `id_vehiculo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_diagnostico` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_vehiculo` (`id_vehiculo` ASC) VISIBLE,
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_diagnostico` (`id_diagnostico` ASC) VISIBLE,
  CONSTRAINT `cita_ibfk_1`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `carworkshop`.`vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cita_ibfk_2`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cita_ibfk_3`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`cliente` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `clientecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_cmxo70m08n43599l3h0h07cc6` (`email` ASC) VISIBLE,
  CONSTRAINT `FKar8ypxyis84ua08105a9v39g8`
    FOREIGN KEY (`email`)
    REFERENCES `carworkshop`.`login` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`cliente_factura_recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`cliente_factura_recibo` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`cliente_factura_recibo` (
  `id_cliente` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `id_recibo` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_factura`, `id_recibo`),
  INDEX `id_factura` (`id_factura` ASC) VISIBLE,
  INDEX `id_recibo` (`id_recibo` ASC) VISIBLE,
  CONSTRAINT `cliente_factura_recibo_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cliente_factura_recibo_ibfk_2`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cliente_factura_recibo_ibfk_3`
    FOREIGN KEY (`id_recibo`)
    REFERENCES `carworkshop`.`recibo` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`empleado` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(50) NOT NULL,
  `puesto` VARCHAR(50) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`encuesta` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`encuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `id_ot` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `puntuacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_ot` (`id_ot` ASC) VISIBLE,
  INDEX `id_factura` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `encuesta_ibfk_1`
    FOREIGN KEY (`id_ot`)
    REFERENCES `carworkshop`.`ot_cabecera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `encuesta_ibfk_2`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`factura_cabecera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`factura_cabecera` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`factura_cabecera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_emision` DATE NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_ot` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_ot` (`id_ot` ASC) VISIBLE,
  CONSTRAINT `factura_cabecera_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_cabecera_ibfk_2`
    FOREIGN KEY (`id_ot`)
    REFERENCES `carworkshop`.`ot_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`factura_linea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`factura_linea` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`factura_linea` (
  `n_linea` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `concepto_pieza` VARCHAR(50) NULL DEFAULT NULL,
  `concepto_mo` VARCHAR(50) NULL DEFAULT NULL,
  `cantidad` FLOAT NOT NULL,
  `precio_unit` FLOAT NOT NULL,
  `id_tipo_iva` INT NOT NULL,
  PRIMARY KEY (`n_linea`, `id_factura`),
  INDEX `id_factura` (`id_factura` ASC) VISIBLE,
  INDEX `concepto_pieza` (`concepto_pieza` ASC) VISIBLE,
  INDEX `concepto_mo` (`concepto_mo` ASC) VISIBLE,
  INDEX `id_tipo_iva` (`id_tipo_iva` ASC) VISIBLE,
  CONSTRAINT `factura_linea_ibfk_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_ibfk_2`
    FOREIGN KEY (`concepto_pieza`)
    REFERENCES `carworkshop`.`factura_linea_pieza` (`concepto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_ibfk_3`
    FOREIGN KEY (`concepto_mo`)
    REFERENCES `carworkshop`.`factura_linea_mo` (`concepto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_ibfk_4`
    FOREIGN KEY (`id_tipo_iva`)
    REFERENCES `carworkshop`.`tipo_iva` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`factura_linea_mo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`factura_linea_mo` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`factura_linea_mo` (
  `id_factura` INT NOT NULL,
  `n_linea` INT NOT NULL,
  `id_pieza` INT NOT NULL,
  `concepto` VARCHAR(50) NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `precio_unit` FLOAT NOT NULL,
  `id_tipo_iva` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `n_linea`),
  UNIQUE INDEX `concepto` (`concepto` ASC) VISIBLE,
  INDEX `id_pieza` (`id_pieza` ASC) VISIBLE,
  INDEX `id_tipo_iva` (`id_tipo_iva` ASC) VISIBLE,
  INDEX `n_linea` (`n_linea` ASC) VISIBLE,
  CONSTRAINT `factura_linea_mo_ibfk_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_mo_ibfk_2`
    FOREIGN KEY (`id_pieza`)
    REFERENCES `carworkshop`.`piezas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_mo_ibfk_3`
    FOREIGN KEY (`id_tipo_iva`)
    REFERENCES `carworkshop`.`tipo_iva` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`factura_linea_pieza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`factura_linea_pieza` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`factura_linea_pieza` (
  `id_factura` INT NOT NULL,
  `n_linea` INT NOT NULL,
  `id_pieza` INT NOT NULL,
  `concepto` VARCHAR(50) NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `precio_unit` FLOAT NOT NULL,
  `id_tipo_iva` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `n_linea`),
  UNIQUE INDEX `concepto` (`concepto` ASC) VISIBLE,
  INDEX `id_pieza` (`id_pieza` ASC) VISIBLE,
  INDEX `id_tipo_iva` (`id_tipo_iva` ASC) VISIBLE,
  INDEX `n_linea` (`n_linea` ASC) VISIBLE,
  CONSTRAINT `factura_linea_pieza_ibfk_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_pieza_ibfk_2`
    FOREIGN KEY (`id_pieza`)
    REFERENCES `carworkshop`.`piezas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `factura_linea_pieza_ibfk_3`
    FOREIGN KEY (`id_tipo_iva`)
    REFERENCES `carworkshop`.`tipo_iva` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`linea_diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`linea_diagnostico` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`linea_diagnostico` (
  `id_diagnostico` INT NOT NULL,
  `n_linea` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `codigo_operario` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `id_tipo_iva` INT NOT NULL,
  PRIMARY KEY (`id_diagnostico`, `n_linea`),
  INDEX `id_tipo_iva` (`id_tipo_iva` ASC) VISIBLE,
  INDEX `codigo_operario` (`codigo_operario` ASC) VISIBLE,
  CONSTRAINT `linea_diagnostico_ibfk_1`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `linea_diagnostico_ibfk_2`
    FOREIGN KEY (`id_tipo_iva`)
    REFERENCES `carworkshop`.`tipo_iva` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `linea_diagnostico_ibfk_3`
    FOREIGN KEY (`codigo_operario`)
    REFERENCES `carworkshop`.`empleado` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`login` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`login` (
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_3cs7dxhnine2f6x5ic4741s6e` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`manoobra_ot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`manoobra_ot` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`manoobra_ot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ot` INT NOT NULL,
  `tarifa` INT NOT NULL,
  `operacion` VARCHAR(50) NOT NULL,
  `ts_inicio` DATETIME NOT NULL,
  `ts_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `id_ot`),
  INDEX `id_ot` (`id_ot` ASC) VISIBLE,
  INDEX `tarifa` (`tarifa` ASC) VISIBLE,
  CONSTRAINT `manoobra_ot_ibfk_1`
    FOREIGN KEY (`id_ot`)
    REFERENCES `carworkshop`.`ot_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `manoobra_ot_ibfk_2`
    FOREIGN KEY (`tarifa`)
    REFERENCES `carworkshop`.`tarifa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`medio_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`medio_pago` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`medio_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`ot_cabecera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`ot_cabecera` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`ot_cabecera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `id_vehiculo` INT NOT NULL,
  `id_diagnostico` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_vehiculo` (`id_vehiculo` ASC) VISIBLE,
  INDEX `id_diagnostico` (`id_diagnostico` ASC) VISIBLE,
  CONSTRAINT `ot_cabecera_ibfk_1`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `carworkshop`.`vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ot_cabecera_ibfk_2`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`ot_totales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`ot_totales` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`ot_totales` (
  `id_ot` INT NOT NULL,
  `total_piezas` INT NULL DEFAULT NULL,
  `total_manoobra` INT NOT NULL,
  `total_tiempo` FLOAT NOT NULL,
  PRIMARY KEY (`id_ot`),
  CONSTRAINT `ot_totales_ibfk_1`
    FOREIGN KEY (`id_ot`)
    REFERENCES `carworkshop`.`ot_cabecera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`piezas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`piezas` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`piezas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`piezas_ot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`piezas_ot` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`piezas_ot` (
  `id_ot` INT NOT NULL AUTO_INCREMENT,
  `id_pieza` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_ot`, `id_pieza`),
  INDEX `id_pieza` (`id_pieza` ASC) VISIBLE,
  CONSTRAINT `piezas_ot_ibfk_1`
    FOREIGN KEY (`id_ot`)
    REFERENCES `carworkshop`.`ot_cabecera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `piezas_ot_ibfk_2`
    FOREIGN KEY (`id_pieza`)
    REFERENCES `carworkshop`.`piezas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`pref_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`pref_cliente` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`pref_cliente` (
  `id_cliente` INT NOT NULL,
  `dia` VARCHAR(50) NOT NULL,
  `turno` VARCHAR(50) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_cliente`, `fecha_hora`),
  CONSTRAINT `pref_cliente_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`recepcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`recepcion` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`recepcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(50) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `id_vehiculo` INT NOT NULL,
  `id_empleado_recepcion` INT NOT NULL,
  `id_diagnostico_inicial` INT NOT NULL,
  `id_diagnostico_recepcion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_vehiculo` (`id_vehiculo` ASC) VISIBLE,
  INDEX `id_diagnostico_inicial` (`id_diagnostico_inicial` ASC) VISIBLE,
  INDEX `id_diagnostico_recepcion` (`id_diagnostico_recepcion` ASC) VISIBLE,
  INDEX `id_empleado_recepcion` (`id_empleado_recepcion` ASC) VISIBLE,
  CONSTRAINT `recepcion_ibfk_1`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `carworkshop`.`vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recepcion_ibfk_2`
    FOREIGN KEY (`id_diagnostico_inicial`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recepcion_ibfk_3`
    FOREIGN KEY (`id_diagnostico_recepcion`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recepcion_ibfk_4`
    FOREIGN KEY (`id_empleado_recepcion`)
    REFERENCES `carworkshop`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`recibo` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`recibo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `importe` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_mediopago` INT NOT NULL,
  PRIMARY KEY (`id`, `id_factura`),
  INDEX `id_mediopago` (`id_mediopago` ASC) VISIBLE,
  CONSTRAINT `recibo_ibfk_1`
    FOREIGN KEY (`id_mediopago`)
    REFERENCES `carworkshop`.`medio_pago` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`sesion` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`sesion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt_iniciosesion` DATETIME NOT NULL,
  `dt_finsesion` DATETIME NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `sesion_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`tarifa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`tarifa` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`tarifa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(50) NOT NULL,
  `tipo_vehiculo` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_vehiculo` (`tipo_vehiculo` ASC) VISIBLE,
  CONSTRAINT `tarifa_ibfk_1`
    FOREIGN KEY (`tipo_vehiculo`)
    REFERENCES `carworkshop`.`tipo_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`tipo_iva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`tipo_iva` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`tipo_iva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`tipo_vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`tipo_vehiculo` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`tipo_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('coche', 'moto', 'camion', 'furgoneta') NOT NULL DEFAULT 'coche',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`totales_diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`totales_diagnostico` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`totales_diagnostico` (
  `id` INT NOT NULL,
  `total_piezas` INT NOT NULL,
  `total_mo` FLOAT NOT NULL,
  `tiempo_total` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `totales_diagnostico_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `carworkshop`.`cabecera_diagnostico` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`totales_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`totales_factura` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`totales_factura` (
  `id_factura` INT NOT NULL,
  `total_piezas` FLOAT NOT NULL,
  `total_mo` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  `total_factura` FLOAT NOT NULL,
  PRIMARY KEY (`id_factura`),
  CONSTRAINT `totales_factura_ibfk_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `carworkshop`.`factura_cabecera` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carworkshop`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carworkshop`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `carworkshop`.`vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(50) NOT NULL,
  `v_year` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `tipo_vehiculo` INT NOT NULL,
  `bastidor` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `tipo_vehiculo` (`tipo_vehiculo` ASC) VISIBLE,
  CONSTRAINT `vehiculo_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carworkshop`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vehiculo_ibfk_2`
    FOREIGN KEY (`tipo_vehiculo`)
    REFERENCES `carworkshop`.`tipo_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
